{% set name = "lsd" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsd-{{ version }}.tar.gz
  sha256: ae0716df1e2d73bbe27de75d3053fbd649b506dc35d100a42e8e0838d9e59632

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - lsd
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jwg4/lsd
  summary: Pounds, shillings and pence conversion
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
