{% set name = "probreg" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/probreg-{{ version }}.tar.gz
  sha256: c615d993bfec3df209e847dc8d40f8dd93d165f7b88d47f1d8ad15a1625c760a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - matplotlib-base
    - open3d
    - pybind11 >=2.2
    - python
    - scikit-learn
    - scipy
    - six
    - transforms3d

test:
  imports:
    - probreg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neka-nat/probreg
  summary: Probablistic point cloud resitration algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - neka-nat
