{% set name = "segment-anything" %}
{% set version = "1.0.0dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/goanpeca/segment-anything/archive/v{{ version }}.tar.gz
  sha256: eb50f08acca71c2de4c416b9ceeab4d2b251cd8e3791d42723423031a8597d57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - pycocotools
    - opencv
    - onnx
    - onnxruntime
    - python >=3.8
    - pytorch >=1.7
    - torchvision >=0.8

test:
  imports:
    - segment_anything
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/segment-anything
  summary: |
    The Segment Anything Model (SAM) produces high quality object masks from input
    prompts such as points or boxes, and it can be used to generate masks for all
    objects in an image. 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
