{% set name = "zarpaint" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarpaint-{{ version }}.tar.gz
  sha256: f73f80d9d517f81a89a5b5b1b15f753ee436e9b1fb8bb404e01c1fc1e67ba714

build:
  entry_points:
    - zarpaint = zarpaint._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - magicgui
    - napari >=0.4.11.dev80
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - pyyaml
    - qtpy
    - scikit-image
    - scipy
    - tensorstore
    - toolz
    - zarr

test:
  imports:
    - zarpaint
  commands:
    - pip list
    - pip check
    - zarpaint --help
  requires:
    - pip

about:
  home: https://github.com/jni/zarpaint
  summary: Paint segmentations directly to on-disk/remote zarr arrays
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - jni
