{% set name = "readlif" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/readlif-{{ version }}.tar.gz
  sha256: 273de3847c9a4c832d9cd486c2bf0656b99f30c157a7781254664bd9c9ccce0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - pillow >=4.2.0
    - python

test:
  imports:
    - readlif
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nimne/readlif
  summary: Fast Leica LIF file reader written in python
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - nimne
