{% set name = "waver" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/waver-{{ version }}.tar.gz
  sha256: e1447a6f083d139ec75e55598dc3300f65cd3baa012568ec1cc79e7de70f6860

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - magicgui >=0.2.10
    - napari >=0.4.10
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - zarr

test:
  imports:
    - waver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sofroniewn/waver
  summary: Wave simulations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
