{% set name = "napari-ids" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_IDS-{{ version }}.tar.gz
  sha256: 5b6e5e2ca206b79920eb23877900a09165994b8287072fe68cff720c7fe59a09

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - numpy
    - opencv
    - python

test:
  imports:
    - napari_ids
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tcotte/napari-IDS
  summary: Plug in which enables to take photo with IDS uEye camera
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
