{% set name = "napari-manual-split-and-merge-labels" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-manual-split-and-merge-labels-{{ version }}.tar.gz
  sha256: 8acced4396721a9fb9886c85f7c51e66bdfa25acc9ec93f0c6da2f436711ae4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7
    - scikit-image

test:
  imports:
    - napari_manual_split_and_merge_labels
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-manual-split-and-merge-labels
  summary: Split and merge labels in napari manually
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
