{% set name = "napari-pymeshlab" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-pymeshlab-{{ version }}.tar.gz
  sha256: 94f98612c01f9a09851c718ce5d5db7f9c04a269cc74959d219b4132849668a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - npe2
    - numpy
    - pymeshlab
    - python >=3.7

test:
  imports:
    - napari_pymeshlab
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zacsimile/napari-pymeshlab
  summary: Interfaces between napari and pymeshlab library to allow import, export and construction of surfaces.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - zacsimile
