{% set name = "napari-clemreg" %}
{% set version = "0.0.1a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-clemreg-{{ version }}.tar.gz
  sha256: 781c62c8c873b520b052d6d1e8d7e7f63ef70360fa9262314959c92520c83b74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - connected-components-3d
    - magicgui
    - napari-plugin-engine >=0.1.4
    - numpy
    - open3d
    - probreg
    - python >=3.7
    - scikit-image
    - scipy
    - transforms3d

test:
  imports:
    - napari_clemreg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/krentzd/napari-clemreg
  summary: A plugin for registering multimodal image volumes based on common segmented structures of interest with point-clouds.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - dkrentzel
