{% set name = "aicspylibczi" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aicspylibczi-{{ version }}.tar.gz
    sha256: b8c2e9360e47ad9c08d9af492bea532daa93f6b73d596fadf683230b212c24e7
  - url: https://github.com/zeiss-microscopy/libCZI/archive/9460669ce533ffb79be0cf41cd3f9d39efd04d31.zip
    sha256: 95f4da7a22bf026d0f31cac1b67a7678dd9f72192e100c21600cebb45514a456
    folder: libCZI
  - url: https://github.com/pybind/pybind11/archive/0bd8896a4010f2d91b2340570c24fa08606ec406.zip
    sha256: b9eb37eb1dd9161e387a2b10fd1ed70e3ad0c3e1c2cb3e75a24f4c41b8fe45ca
    folder: pybind11

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    # - libpng
    - python
    - pip
    # - pytest-runner
    # - zlib
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - aicspylibczi
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AllenCellModeling/aicspylibczi
  summary: A python module and a python extension for Zeiss (CZI/ZISRAW) microscopy files.
  license: LGPL-3.0 & GPL-3.0 & BSD-3-Clause
  license_file:
    - LICENSE
    - pybind11/LICENSE
    - libCZI/COPYING.LESSER
    - libCZI/COPYING

extra:
  recipe-maintainers:
    - evamaxfield
    - goanpeca
