{% set name = "miplib" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/miplib-{{ version }}.tar.gz
  sha256: 0dda3c3fd175509d6ffdfa655f434c10be708dd19bce48126e21188ff92f205a

build:
  entry_points:
    - miplib.import = miplib.bin.import:main
    - miplib.correlatem = miplib.bin.correlatem:main
    - miplib.fuse = miplib.bin.fuse:main
    - miplib.register = miplib.bin.register:main
    - miplib.resolution = miplib.bin.resolution:main
    - miplib.ism = miplib.bin.ism:main
    - pyimq.main = miplib.bin.pyimq:main
    - pyimq.subjective = miplib.bin.subjective:main
    - pyimq.power = miplib.bin.power:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - h5py
    - jpype1
    - matplotlib-base
    - pandas
    - pims
    - psf
    - python
    - scikit-image
    - scipy
    - simpleitk
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - miplib
  commands:
    - pip list
    - pip check
    - miplib.import --help
    - miplib.correlatem --help
    - miplib.fuse --help
    - miplib.register --help
    - miplib.resolution --help
    - miplib.ism --help
    - pyimq.main --help
    - pyimq.subjective --help
    - pyimq.power --help
  requires:
    - pip

about:
  home: https://pypi.org/project/miplib/
  summary: A Python software library for (optical) microscopy image restoration, reconstruction and analysis.
  license: BSD-Protection
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - goanpeca
