{% set name = "napari-bacseg" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-bacseg-{{ version }}.tar.gz
  sha256: e8629d6257db5bd734158472c10ab82617bd7321c241b22d902d85e5ff9ba8f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - napari ==0.4.16
    - numpy ==1.23.5
    - qtpy
    - cellpose >=2.1.1
    - numba >=0.43.1
    - scipy
    - pytorch
    - opencv-python-headless
    - natsort
    - tqdm
    - imagecodecs
    - tifffile
    - pandas
    - mat4py
    - glob2
    - matplotlib-base
    - scikit-image
    - roifile
    - openpyxl
    - shapely
    - colicoords
    - psutil
    - xmltodict
    - astropy
    - tiler
    - imageio-ffmpeg

test:
  imports:
    - napari_bacseg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/piedrro/napari-bacseg
  summary: Bacterial segmentation and analysis platform than can inport/export files in multiple formats. Integrating many tools such as Cellpose, ColiCoords, Oufti/MicrobeTracker.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
