{% set name = "PyMeshLab" %}
{% set version = "2021.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cnr-isti-vclab/PyMeshLab/archive/v2021.10.tar.gz
  sha256: 8b4752e3d43524c964818a75903cf86cb39106d02e7e8b124b25da6ab7416ab1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - numpy
    - python

test:
  imports:
    - pymeshlab
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cnr-isti-vclab/PyMeshLab
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alemuntoni
    - goanpeca
