{% set name = "RedLionfish" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RedLionfish-{{ version }}.tar.gz
  sha256: 2590ac98a91e0ace4d081af8a424d7f7018f48ac8fe55a176378200249d95ece

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - RedLionfishDeconv
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  summary: Fast Richardson-Lucy deconvolution of 3D volume data using GPU or CPU with napari plugin.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
