{% set name = "flimlib" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 6dc0ffb11b98ec8dca1779f04851871c3b4f06071fb39d4e6e081b6d8874d2af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - gcc
    - pip
    - python >=3.8
    - wheel
  run:
    - numpy >=1.12.0
    - python >=3.8

test:
  imports:
    - flimlib
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flimlib/flimlib
  summary: A python wrapper for flimlib's C functions
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
