{% set name = "flimlib" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flimlib-{{ version }}.tar.gz
  sha256: 8cbbf2a727a378b6e3aff969ad264825fca7b5b7bb566cc00e8abf5c6d0fca62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.12.0

test:
  imports:
    - flimlib
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flimlib/flimlib
  summary: A python wrapper for flimlib's C functions
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
