{% set name = "brainreg" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-{{ version }}.tar.gz
  sha256: 2a9313ff4087cc5639253f0b882b75946f530e6934d5b1a13daae496714f6261

build:
  entry_points:
    - brainreg = brainreg.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bg-atlasapi
    - bg-space
    - brainglobe-napari-io
    - brainreg-segment >=0.0.2
    - configobj
    - configparser
    - fancylog
    - imio
    - imlib >=0.0.26
    - multiprocessing-logging
    - napari >=0.3.7
    - numpy
    - python >=3.7
    - scikit-image
    - slurmio

test:
  imports:
    - brainreg
  commands:
    - pip list
    - pip check
    - brainreg --help
  requires:
    - pip

about:
  home: https://pypi.org/project/brainreg/
  summary: Automated 3D brain registration
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - goanpeca
