{% set name = "zenodo-get" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zenodo_get-{{ version }}.tar.gz
  sha256: d595ebfe7bbad2217bf7f3b7923a0daa9d36751248f1ebeab0f425143061a033

build:
  entry_points:
    - zenodo_get = zenodo_get.zget:zenodo_get
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - wget

test:
  imports:
    - zenodo_get
  commands:
    - pip list
    - pip check
    - zenodo_get --help
  requires:
    - pip

about:
  home: https://gitlab.com/dvolgyes/zenodo_get
  summary: Zenodo_get - a downloader for Zenodo records
  license: AGPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
