{% set name = "napari-svetlana" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_svetlana-{{ version }}.tar.gz
  sha256: d7ed1921bdab111aafb98079d99f96d23eece05b59f3254dd8658690cdb3f282

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - napari-plugin-engine >=0.1.4
    - numpy
    - albumentations ==1.0.3
    - joblib ==1.1.0
    - light-the-torch
    - matplotlib-base
    - opencv ==4.5.5.62
    - pyqt
    - cucim ==22.6.0  # [linux]
    - cupy-cuda102 ==10.6.0
    - xlsxwriter
    - pandas

test:
  imports:
    - napari_svetlana
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-svetlana/
  summary: A classification plugin for the ROIs of a segmentation mask.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
