{% set name = "viz-oneat" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viz-oneat-{{ version }}.tar.gz
  sha256: f823023f43647698cd75737e2e4c9ac9e234745e127a6a064b1b244c0d28b8d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - oneat

test:
  imports:
    - vnet
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/VNet/
  summary: Neural network activation visualization tool.
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - goanpeca
