{% set name = "napari-tracing" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tracing-{{ version }}.tar.gz
  sha256: 5212bfa254910abd9b2714393d34328463bd1c9fb9b7f2aa1a4d1e2a64202c1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - qtpy
    - brightest-path-lib

test:
  imports:
    - napari_tracing
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapmanager/napari-tracing
  summary: A plugin to trace the brightest path between two points in an image
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
