{% set name = "napari-chatgpt" %}
{% set version = "2023.5.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-chatgpt-{{ version }}.tar.gz
  sha256: dc45878e26fcef2c8e898762ffe31bbdfae10028ca8321368d93cb5d94319c5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - magicgui
    - scikit-image
    - qtpy
    - langchain ==0.0.167
    - fastapi
    - uvicorn
    - websockets
    - openai
    - tiktoken
    - wikipedia
    - lxml
    - gtts
    - playsound
    - matplotlib-base
    - xarray
    - arbol
    - playwright
    - duckduckgo-search
    - ome-zarr
    - scikit-video
    - pygpt4all ==1.1.0
    - googlebard ==1.0.2

test:
  imports:
    - napari_chatgpt
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/royerlab/napari-chatgpt
  summary: A napari plugin to process and analyse images with chatGPT.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
