{% set name = "napari-nucleaizer" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/etasnadi/napari_nucleaizer/archive/refs/tags/v{{ version }}}.tar.gz
  sha256: 2b120ee5786e3360b4cd255e60fb48ec6959de6b6d8aa52a0f4ff38c73d7f576

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - napari-plugin-engine>=0.1.4
    - numpy
    - scikit-image
    - nucleaizer_backend

test:
  imports:
    - napari_nucleaizer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/etasnadi/napari_nucleaizer
  summary: GUI for the nucleaAIzer method in Napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
