{% set name = "napari-flowering-apple-tree-pixel-classification" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-flowering-apple-tree-pixel-classification-{{ version }}.tar.gz
  sha256: 363d751c28f32ce45d5d49845da94f673a530aa41f9c0487d4de8529d3adb26b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - scikit-image
    - tensorflow

test:
  imports:
    - napari_flowering_apple_tree_pixel_classification
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hereariim/napari-flowering-apple-tree-pixel-classification
  summary: Get flowering apple tree based on UNET algorithm
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
