{% set name = "elastix-napari" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elastix_napari-{{ version }}.tar.gz
  sha256: ef772eaf3cc841fa14743fdc59c77b21446eda9870e959336a514df162bbad86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - itk-elastix >=0.11.1
    - itk-napari-conversion >=0.3.1
    - magicgui >=0.2.6
    - napari >=0.4.6
    - napari-itk-io >=0.1.0
    - napari-plugin-engine >=0.1.4
    - numpy >=1.19.0
    - python >=3.6

test:
  imports:
    - elastix_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SuperElastix/elastix_napari
  summary: A toolbox for rigid and nonrigid registration of images.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ViktorvdValk
    - conda-forge/napari
