{% set name = "napari-imagej" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-imagej-{{ version }}.tar.gz
  sha256: 69f1dffc8d39197f09b64e351797f661634f2f718cc999519a7d253cf3901c86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - confuse
    - imglyb >=2.1.0
    - jpype1 >=1.4.1
    - labeling >=0.1.12
    - magicgui >=0.5.1
    - napari >=0.4.17
    - numpy
    - pandas
    - pyimagej >=1.4.1
    - python >=3.8,<3.11
    - scyjava >=1.8.1
    - qtconsole !=5.4.2
    - typing-extensions !=4.6.0

test:
  imports:
    - napari_imagej
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/imagej/napari-imagej
  summary: ImageJ functionality from napari
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
