{% set name = "brightest-path-lib" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brightest-path-lib-{{ version }}.tar.gz
  sha256: 9aae1c956ab2a014b6fbfb1a69c5cd2585d9ad508f6baa90e0f99ebdce2aae57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - gcc
    - numpy
    - pip
    - psutil
    - python >=3.7
    - pythran
    - setuptools
    - transonic
    - wheel
  run:
    - python >=3.7
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - brightest_path_lib
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapmanager/brightest-path-lib
  summary: A library of path-finding algorithms to find the brightest path between two points in an image.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
